---

inputs:
  step-outcome:
    description: 'Outcome of the interesting step'
    required: true
  expected-failure:
    description: 'Whether a failure is expected'
    required: true

runs:
  using: composite

  steps:
    - if: ${{ inputs.step-outcome == 'success'
              && inputs.expected-failure != 'expected-failure' }}
      shell: bash
      run: |
        echo "The step succeeded and was planned to succeed."
        exit 0

    - if: ${{ inputs.step-outcome != 'success'
              && matrix.expected-failure == 'expected-failure' }}
      shell: bash
      run: |
        echo "The step failed and was planned to fail."
        exit 0

    - if: ${{ inputs.step-outcome == 'success'
              && matrix.expected-failure == 'expected-failure' }}
      shell: bash
      run: |
        echo "The step succeeded but was planned to fail."
        exit 1

    - if: ${{ inputs.step-outcome == 'failure'
              && matrix.expected-failure != 'expected-failure' }}
      shell: bash
      run: |
        echo "The step failed but was planned to fail."
        exit 1
