[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/nickel-lang/tree-sitter-nickel?rev=b1a4718601ebd29a62bf3a7fd1069a99ccf48093"]
git = "https://github.com/nickel-lang/tree-sitter-nickel"
rev = "b1a4718601ebd29a62bf3a7fd1069a99ccf48093"
replace-with = "vendored-sources"

[source."git+https://github.com/nvim-treesitter/tree-sitter-query"]
git = "https://github.com/nvim-treesitter/tree-sitter-query"
replace-with = "vendored-sources"

[source."git+https://github.com/tree-sitter/tree-sitter-bash"]
git = "https://github.com/tree-sitter/tree-sitter-bash"
replace-with = "vendored-sources"

[source."git+https://github.com/tree-sitter/tree-sitter-ocaml"]
git = "https://github.com/tree-sitter/tree-sitter-ocaml"
replace-with = "vendored-sources"

[source."git+https://github.com/tweag/tree-sitter-facade"]
git = "https://github.com/tweag/tree-sitter-facade"
replace-with = "vendored-sources"

[source."git+https://github.com/tweag/web-tree-sitter-sys"]
git = "https://github.com/tweag/web-tree-sitter-sys"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
