name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

## We specify a concurrency group with automated cancellation. This means that
## other pushes on the same `github.ref` (eg. other pushes to the same pull
## request) cancel previous occurrences of the CI.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    name: Linux

    strategy:
      fail-fast: false
      matrix:
        tag:
          - alpine
          - archlinux
          - centos
          - debian
          - debian-testing
          - debian-unstable
          - fedora
          - oraclelinux
          - opensuse
          - ubuntu
          - ubuntu-lts

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build \
            . \
            --tag topiary \
            --file .github/workflows/ci.dockerfile \
            --build-arg tag=${{matrix.tag}}

      - name: Run a tiny smoke test
        run: |
          echo 'open Foo' > expected.ml
          echo 'open  Foo' \
            | docker run --interactive topiary --language ocaml \
            > result.ml
          diff expected.ml result.ml

      ## NOTE: Proper tests are disabled because they actually do not pass for
      ## Topiary v0.1.0. These should be re-enabled in future versions.

      # - name: Run tests
      #   run: |
      #     set -euC
      #     ## Test on OCaml implementation files (.ml)
      #     cat topiary/tests/samples/input/ocaml.ml \
      #       | docker run --interactive topiary --language ocaml-implementation \
      #       > ocaml.ml
      #     diff topiary/tests/samples/expected/ocaml.ml ocaml.ml
      #     ## Test on OCaml interface files (.mli)
      #     cat topiary/tests/samples/input/ocaml.mli \
      #       | docker run --interactive topiary --language ocaml-interface \
      #       > ocaml.mli
      #     diff topiary/tests/samples/expected/ocaml.mli ocaml.mli

  windows:
    name: Windows

    strategy:
      fail-fast: false
      matrix:
        tag:
          - windows-mingw
          - windows-msvc

    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        shell: bash
        run: |
          docker build \
            . \
            --tag topiary \
            --file .github/workflows/ci.dockerfile \
            --build-arg tag=${{matrix.tag}}

      - name: Run a tiny smoke test
        shell: bash
        run: |
          echo 'open Foo' > expected.ml
          echo 'open  Foo' \
            | docker run --interactive topiary --language ocaml \
            > result.ml
          diff expected.ml result.ml

      ## NOTE: Proper tests are disabled because they actually do not pass for
      ## Topiary v0.1.0. These should be re-enabled in future versions.

      # - name: Run tests
      #   shell: bash
      #   run: |
      #     set -euC
      #     ## Test on OCaml implementation files (.ml)
      #     cat topiary/tests/samples/input/ocaml.ml \
      #       | docker run --interactive topiary --language ocaml-implementation \
      #       > ocaml.ml
      #     diff topiary/tests/samples/expected/ocaml.ml ocaml.ml
      #     ## Test on OCaml interface files (.mli)
      #     cat topiary/tests/samples/input/ocaml.mli \
      #       | docker run --interactive topiary --language ocaml-interface \
      #       > ocaml.mli
      #     diff topiary/tests/samples/expected/ocaml.mli ocaml.mli
